//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Regalia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateandTime { get; set; }
        public string CeremonyType { get; set; }
        public string CapSize { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> HeightFeet { get; set; }
        public Nullable<int> HeightInches { get; set; }
        public string Degree { get; set; }
        public string College { get; set; }
        public string CollegeCity { get; set; }
        public string CollegeState { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
