//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Castest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitutionCampus
    {
        public double DapipId { get; set; }
        public Nullable<double> OpeId { get; set; }
        public Nullable<double> IpedsUnitIds { get; set; }
        public string LocationName { get; set; }
        public string ParentName { get; set; }
        public string ParentDapipId { get; set; }
        public string LocationType { get; set; }
        public string Address { get; set; }
        public Nullable<double> GeneralPhone { get; set; }
        public string AdminName { get; set; }
        public Nullable<double> AdminPhone { get; set; }
        public string AdminEmail { get; set; }
        public Nullable<double> Fax { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
